### ISSUE TITLE
Error when testing call process and after subscribe

### ISSUE THREAD

**Issue by ilajosmanov** [logux/backend-test#2]
So, I have the error when calling process and then subscribe on the channel
But if I switch (first a channel and second process) — have no error

DB: MongoDB

```
await client1.process(createHardware(doc));
await client2.subscribe("@hardware")
```

```
RangeError: Maximum call stack size exceeded

      at clone (node_modules/@logux/core/test-pair/index.cjs:3:16)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at node_modules/@logux/core/test-pair/index.cjs:5:25
          at Array.map (<anonymous>)
      at clone (node_modules/@logux/core/test-pair/index.cjs:5:16)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at node_modules/@logux/core/test-pair/index.cjs:5:25
          at Array.map (<anonymous>)
      at clone (node_modules/@logux/core/test-pair/index.cjs:5:16)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at clone (node_modules/@logux/core/test-pair/index.cjs:9:19)
      at node_modules/@logux/core/test-pair/index.cjs:5:25
          at Array.map (<anonymous>)
      at clone (node_modules/@logux/core/test-pair/index.cjs:5:16)
```

**Comment by ai** [comment]
Do you call it in your code for Logux Server? Or why do you open a Logux Back-end Test?

Show the full code of the server, if it is a Logux Server problem.

**Comment by ilajosmanov** [comment]
From test server
