### ISSUE TITLE
Can't pass wrongSubprotocol error assert

### ISSUE THREAD

**Issue by egregors** [logux/backend-test#6]
Step 6 "Checks users subprotocol"

I find error format in the Spec: https://logux.io/protocols/backend/spec/
```JSON
{
  "answer": "wrongSubprotocol",
  "supported": string
}
```
So, as the answer I sent:
```bash
2020-07-15 08:58:02,678 - logux.views - DEBUG - got auth cmd: {'command': 'auth', 'authId': 'rSecXfrA4Hdzf2s1RNK1E', 'userId': '10', 'token': '10:good', 'headers': {}, 'cookie': {}, 'subprotocol': '0.9.1'}
2020-07-15 08:58:02,679 - logux.core - WARNING - unsupported subprotocol version: 0.9.1 expected: ^1.0.0
2020-07-15 08:58:02,679 - logux.views - DEBUG - {'answer': 'wrongSubprotocol', 'supported': '^1.0.0'}
```

But backend-test expect something like (@logux/backend-test/tests/auth.js:61): `'^1.0.0 application subprotocols are supported, but you use 0.9.1'`, so I got error as result:
```bash
Re-run test: npx @logux/backend-test http://localhost:8000/logux/ 6

Error: Wrong credentials
    at /Users/egregors/Documents/GitHub/django/lbt/node_modules/@logux/server/test-client/index.js:51:18
    at Object.emit (/Users/egregors/Documents/GitHub/django/lbt/node_modules/nanoevents/index.cjs:5:7)
    at ClientNode.syncError (/Users/egregors/Documents/GitHub/django/lbt/node_modules/@logux/core/base-node/index.cjs:221:18)
    at ClientNode.errorMessage (/Users/egregors/Documents/GitHub/django/lbt/node_modules/@logux/core/error/index.cjs:10:8)
    at ClientNode.onMessage (/Users/egregors/Documents/GitHub/django/lbt/node_modules/@logux/core/base-node/index.cjs:193:27)
    at /Users/egregors/Documents/GitHub/django/lbt/node_modules/@logux/core/base-node/index.cjs:88:14
    at Object.emit (/Users/egregors/Documents/GitHub/django/lbt/node_modules/nanoevents/index.cjs:5:7)
    at Timeout._onTimeout (/Users/egregors/Documents/GitHub/django/lbt/node_modules/@logux/core/local-pair/index.cjs:59:30)
    at listOnTimeout (internal/timers.js:551:17)
    at processTimers (internal/timers.js:494:7)

```

**Comment by ai** [comment]
Fixed https://github.com/logux/docs/commit/2f66762f22f26df294e11f6f423822511742ff8c

**Comment by ai** [comment]
You need to add `authId` to `wrongSubprotocol` as well. Otherwise Logux Proxy will know what do you answer for.
